package org.openapi.quarkus.pokemon_yaml.api.auth;

import jakarta.annotation.PostConstruct;
import jakarta.ws.rs.Priorities;

import jakarta.annotation.Priority;

import io.quarkiverse.openapi.generator.OpenApiGeneratorConfig;

import io.quarkiverse.openapi.generator.providers.BasicAuthenticationProvider;
import io.quarkiverse.openapi.generator.providers.ApiKeyAuthenticationProvider;
import io.quarkiverse.openapi.generator.providers.ApiKeyIn;
import io.quarkiverse.openapi.generator.providers.AbstractCompositeAuthenticationProvider;
import io.quarkiverse.openapi.generator.providers.OperationAuthInfo;

@Priority(Priorities.AUTHENTICATION)
public class CompositeAuthenticationProvider extends AbstractCompositeAuthenticationProvider {

    @jakarta.inject.Inject
    OpenApiGeneratorConfig generatorConfig;


    @PostConstruct
    public void init() {

        BasicAuthenticationProvider basicAuthProvider0 = new BasicAuthenticationProvider("org/openapi/quarkus/pokemon_yaml", sanitizeAuthName("basicAuth"), generatorConfig);
        this.addAuthenticationProvider(basicAuthProvider0);
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/ability/")
            .withId("abilityList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/ability/{id}/")
            .withId("abilityRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry/")
            .withId("berryList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry/{id}/")
            .withId("berryRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry-firmness/")
            .withId("berryFirmnessList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry-firmness/{id}/")
            .withId("berryFirmnessRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry-flavor/")
            .withId("berryFlavorList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry-flavor/{id}/")
            .withId("berryFlavorRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/characteristic/")
            .withId("characteristicList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/characteristic/{id}/")
            .withId("characteristicRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/contest-effect/")
            .withId("contestEffectList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/contest-effect/{id}/")
            .withId("contestEffectRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/contest-type/")
            .withId("contestTypeList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/contest-type/{id}/")
            .withId("contestTypeRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/egg-group/")
            .withId("eggGroupList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/egg-group/{id}/")
            .withId("eggGroupRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-condition/")
            .withId("encounterConditionList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-condition/{id}/")
            .withId("encounterConditionRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-condition-value/")
            .withId("encounterConditionValueList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-condition-value/{id}/")
            .withId("encounterConditionValueRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-method/")
            .withId("encounterMethodList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-method/{id}/")
            .withId("encounterMethodRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/evolution-chain/")
            .withId("evolutionChainList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/evolution-chain/{id}/")
            .withId("evolutionChainRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/evolution-trigger/")
            .withId("evolutionTriggerList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/evolution-trigger/{id}/")
            .withId("evolutionTriggerRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/gender/")
            .withId("genderList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/gender/{id}/")
            .withId("genderRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/generation/")
            .withId("generationList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/generation/{id}/")
            .withId("generationRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/growth-rate/")
            .withId("growthRateList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/growth-rate/{id}/")
            .withId("growthRateRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item/")
            .withId("itemList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item/{id}/")
            .withId("itemRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-attribute/")
            .withId("itemAttributeList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-attribute/{id}/")
            .withId("itemAttributeRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-category/")
            .withId("itemCategoryList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-category/{id}/")
            .withId("itemCategoryRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-fling-effect/")
            .withId("itemFlingEffectList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-fling-effect/{id}/")
            .withId("itemFlingEffectRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-pocket/")
            .withId("itemPocketList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-pocket/{id}/")
            .withId("itemPocketRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/language/")
            .withId("languageList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/language/{id}/")
            .withId("languageRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/location/")
            .withId("locationList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/location/{id}/")
            .withId("locationRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/location-area/")
            .withId("locationAreaList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/location-area/{id}/")
            .withId("locationAreaRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/machine/")
            .withId("machineList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/machine/{id}/")
            .withId("machineRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move/")
            .withId("moveList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move/{id}/")
            .withId("moveRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-ailment/")
            .withId("moveAilmentList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-ailment/{id}/")
            .withId("moveAilmentRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-battle-style/")
            .withId("moveBattleStyleList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-battle-style/{id}/")
            .withId("moveBattleStyleRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-category/")
            .withId("moveCategoryList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-category/{id}/")
            .withId("moveCategoryRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-damage-class/")
            .withId("moveDamageClassList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-damage-class/{id}/")
            .withId("moveDamageClassRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-learn-method/")
            .withId("moveLearnMethodList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-learn-method/{id}/")
            .withId("moveLearnMethodRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-target/")
            .withId("moveTargetList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-target/{id}/")
            .withId("moveTargetRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/nature/")
            .withId("natureList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/nature/{id}/")
            .withId("natureRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pal-park-area/")
            .withId("palParkAreaList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pal-park-area/{id}/")
            .withId("palParkAreaRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokeathlon-stat/")
            .withId("pokeathlonStatList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokeathlon-stat/{id}/")
            .withId("pokeathlonStatRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokedex/")
            .withId("pokedexList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokedex/{id}/")
            .withId("pokedexRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon/{pokemon_id}/encounters")
            .withId("pokemonEncountersRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon/")
            .withId("pokemonList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon/{id}/")
            .withId("pokemonRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-color/")
            .withId("pokemonColorList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-color/{id}/")
            .withId("pokemonColorRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-form/")
            .withId("pokemonFormList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-form/{id}/")
            .withId("pokemonFormRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-habitat/")
            .withId("pokemonHabitatList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-habitat/{id}/")
            .withId("pokemonHabitatRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-shape/")
            .withId("pokemonShapeList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-shape/{id}/")
            .withId("pokemonShapeRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-species/")
            .withId("pokemonSpeciesList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-species/{id}/")
            .withId("pokemonSpeciesRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/region/")
            .withId("regionList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/region/{id}/")
            .withId("regionRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/schema/")
            .withId("schemaRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/stat/")
            .withId("statList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/stat/{id}/")
            .withId("statRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/super-contest-effect/")
            .withId("superContestEffectList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/super-contest-effect/{id}/")
            .withId("superContestEffectRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/type/")
            .withId("typeList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/type/{id}/")
            .withId("typeRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/version/")
            .withId("versionList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/version/{id}/")
            .withId("versionRetrieve")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/version-group/")
            .withId("versionGroupList")
            .withMethod("GET")
            .build());
        basicAuthProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/version-group/{id}/")
            .withId("versionGroupRetrieve")
            .withMethod("GET")
            .build());
        ApiKeyAuthenticationProvider apiKeyCookieProvider0 = new ApiKeyAuthenticationProvider("org/openapi/quarkus/pokemon_yaml", sanitizeAuthName("cookieAuth"), ApiKeyIn.cookie, "sessionid", generatorConfig);
        this.addAuthenticationProvider(apiKeyCookieProvider0);
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/ability/")
            .withId("abilityList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/ability/{id}/")
            .withId("abilityRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry/")
            .withId("berryList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry/{id}/")
            .withId("berryRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry-firmness/")
            .withId("berryFirmnessList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry-firmness/{id}/")
            .withId("berryFirmnessRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry-flavor/")
            .withId("berryFlavorList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/berry-flavor/{id}/")
            .withId("berryFlavorRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/characteristic/")
            .withId("characteristicList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/characteristic/{id}/")
            .withId("characteristicRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/contest-effect/")
            .withId("contestEffectList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/contest-effect/{id}/")
            .withId("contestEffectRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/contest-type/")
            .withId("contestTypeList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/contest-type/{id}/")
            .withId("contestTypeRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/egg-group/")
            .withId("eggGroupList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/egg-group/{id}/")
            .withId("eggGroupRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-condition/")
            .withId("encounterConditionList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-condition/{id}/")
            .withId("encounterConditionRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-condition-value/")
            .withId("encounterConditionValueList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-condition-value/{id}/")
            .withId("encounterConditionValueRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-method/")
            .withId("encounterMethodList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/encounter-method/{id}/")
            .withId("encounterMethodRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/evolution-chain/")
            .withId("evolutionChainList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/evolution-chain/{id}/")
            .withId("evolutionChainRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/evolution-trigger/")
            .withId("evolutionTriggerList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/evolution-trigger/{id}/")
            .withId("evolutionTriggerRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/gender/")
            .withId("genderList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/gender/{id}/")
            .withId("genderRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/generation/")
            .withId("generationList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/generation/{id}/")
            .withId("generationRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/growth-rate/")
            .withId("growthRateList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/growth-rate/{id}/")
            .withId("growthRateRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item/")
            .withId("itemList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item/{id}/")
            .withId("itemRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-attribute/")
            .withId("itemAttributeList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-attribute/{id}/")
            .withId("itemAttributeRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-category/")
            .withId("itemCategoryList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-category/{id}/")
            .withId("itemCategoryRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-fling-effect/")
            .withId("itemFlingEffectList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-fling-effect/{id}/")
            .withId("itemFlingEffectRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-pocket/")
            .withId("itemPocketList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/item-pocket/{id}/")
            .withId("itemPocketRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/language/")
            .withId("languageList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/language/{id}/")
            .withId("languageRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/location/")
            .withId("locationList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/location/{id}/")
            .withId("locationRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/location-area/")
            .withId("locationAreaList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/location-area/{id}/")
            .withId("locationAreaRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/machine/")
            .withId("machineList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/machine/{id}/")
            .withId("machineRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move/")
            .withId("moveList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move/{id}/")
            .withId("moveRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-ailment/")
            .withId("moveAilmentList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-ailment/{id}/")
            .withId("moveAilmentRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-battle-style/")
            .withId("moveBattleStyleList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-battle-style/{id}/")
            .withId("moveBattleStyleRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-category/")
            .withId("moveCategoryList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-category/{id}/")
            .withId("moveCategoryRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-damage-class/")
            .withId("moveDamageClassList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-damage-class/{id}/")
            .withId("moveDamageClassRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-learn-method/")
            .withId("moveLearnMethodList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-learn-method/{id}/")
            .withId("moveLearnMethodRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-target/")
            .withId("moveTargetList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/move-target/{id}/")
            .withId("moveTargetRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/nature/")
            .withId("natureList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/nature/{id}/")
            .withId("natureRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pal-park-area/")
            .withId("palParkAreaList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pal-park-area/{id}/")
            .withId("palParkAreaRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokeathlon-stat/")
            .withId("pokeathlonStatList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokeathlon-stat/{id}/")
            .withId("pokeathlonStatRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokedex/")
            .withId("pokedexList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokedex/{id}/")
            .withId("pokedexRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon/{pokemon_id}/encounters")
            .withId("pokemonEncountersRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon/")
            .withId("pokemonList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon/{id}/")
            .withId("pokemonRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-color/")
            .withId("pokemonColorList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-color/{id}/")
            .withId("pokemonColorRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-form/")
            .withId("pokemonFormList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-form/{id}/")
            .withId("pokemonFormRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-habitat/")
            .withId("pokemonHabitatList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-habitat/{id}/")
            .withId("pokemonHabitatRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-shape/")
            .withId("pokemonShapeList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-shape/{id}/")
            .withId("pokemonShapeRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-species/")
            .withId("pokemonSpeciesList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/pokemon-species/{id}/")
            .withId("pokemonSpeciesRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/region/")
            .withId("regionList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/region/{id}/")
            .withId("regionRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/schema/")
            .withId("schemaRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/stat/")
            .withId("statList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/stat/{id}/")
            .withId("statRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/super-contest-effect/")
            .withId("superContestEffectList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/super-contest-effect/{id}/")
            .withId("superContestEffectRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/type/")
            .withId("typeList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/type/{id}/")
            .withId("typeRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/version/")
            .withId("versionList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/version/{id}/")
            .withId("versionRetrieve")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/version-group/")
            .withId("versionGroupList")
            .withMethod("GET")
            .build());
        apiKeyCookieProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/api/v2/version-group/{id}/")
            .withId("versionGroupRetrieve")
            .withMethod("GET")
            .build());
    }

}